site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:8001", "s201:8101"]
    - ["s102:8002", "s202:8102"]

process:
  s101: localhost
  s102: localhost
  s201: p1
  s202: p1

# process_name - host_addr map
host:
  localhost: 127.0.0.1
  p1: 127.0.0.1
