matrix:
    include:
        - os: osx
        - os: linux
          dist: trusty
          sudo: required
          services: docker

language: cpp

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost || true; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew install yaml-cpp || true;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python || true; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip2 install tabulate; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker pull ubuntu:16.04;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker run -w /root --name test -d ubuntu:16.04 sleep infinity;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker cp . test:/root/janus;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker exec test apt-get update -qq;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker exec test apt-get install -y git pkg-config build-essential python-dev python-pip libgoogle-perftools-dev cmake;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker exec test pip install tabulate;
      fi

install:

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./waf configure build; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker exec test sh -c 'cd janus && cmake . && make';
      fi

