# yaml-cpp online: https://yaml-online-parser.appspot.com/
# suppose m shards and n warehouse each shard; 
# the first replica to be the leader by default
# https://aju9mlkupe.feishu.cn/docs/doccnG7AZ1gjFmo9CcgRMidJO5f Port allocation policy

shards: 2  # number of shards
replicas: 3  # number of replicas
warehouses: w_id  # number of warehouses per shard, keep same as the tpcc worker threads
localhost:
  - name: shard0
    index: 0
    ip:   ip_shard0_localhost
    port: 31000
  - name: shard1
    index: 1
    ip:   ip_shard1_localhost
    port: 31100
p1:
  - name: shard0
    index: 0
    ip:  ip_shard0_p1
    port: 32000
  - name: shard1
    index: 1
    ip: ip_shard1_p1
    port: 32100
p2:
  - name: shard0
    index: 0
    ip:  ip_shard0_p2
    port: 33000
  - name: shard1
    index: 1
    ip:  ip_shard1_p2
    port: 33100
learner:
 - name: shard0
   index: 0
   ip:  ip_shard0_learner
   port: 34000
 - name: shard1
   index: 1
   ip:  ip_shard1_learner
   port: 34100
memlocalhost: 6001 # mem control port
memlearner: 6001
memp1: 6002
memp2: 6003
