site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:8001", "s201:8101"] #, "s301:8002"]

process:
  s101: localhost
  s102: localhost
  s103: localhost
  s104: localhost
  s105: localhost
  s106: localhost
  s107: localhost
  s108: localhost
  s109: localhost
  s110: localhost
  s111: localhost
  s112: localhost
  s113: localhost
  s114: localhost
  s115: localhost
  s116: localhost
  s117: localhost
  s118: localhost
  s119: localhost
  s120: localhost
  s121: localhost
  s122: localhost
  s123: localhost
  s124: localhost

  s201: p1
  s202: p1
  s203: p1
  s204: p1
  s205: p1
  s206: p1
  s207: p1
  s208: p1
  s209: p1
  s210: p1
  s211: p1
  s212: p1
  s213: p1
  s214: p1
  s215: p1
  s216: p1
  s217: p1
  s218: p1
  s219: p1
  s220: p1
  s221: p1
  s222: p1
  s223: p1
  s224: p1

# process_name - host_addr map
host:
  localhost: 10.1.0.7 
  p1: 10.1.0.8
