#
# host machine
#   physical process as container  
#     logical site as a thread
# site --> process --> host
#   
# site: logical site (either as server/coordinator), which lives in a thread (may share thread 
# process 
# host is  

# site - partition map
site:
  server: # each line is a partition, the first is the master site_name:port
     - ["s101:8100"] #, "s201:8101" , "s301:8102" , "s401:8103" , "s501:8104"]
#    - ["s102:8100", "s202:8101", "s302:8102"]
#    - ["s103:8200", "s203:8201", "s303:8202"]
#    - ["s101:8101"]
#    - ["s102:8102"]
#    - ["s103:8103"]
  client: # each line is a partition
    - ["c101"]
#    - ["c102"]

# site_name - process_name map
process:
  s101: localhost
  s201: localhost
  s301: localhost
  s401: localhost
  s501: localhost
  c101: localhost

# process_name - host_addr map
host:
  localhost: 127.0.0.1

